# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('results', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[(b'team', b'TEAM'), (b'indv', b'INDIVIDUAL')], max_length=48)),
                ('ramp', models.CharField(max_length=128)),
                ('lake', models.CharField(choices=[(b'lbj', b'LBJ'), (b'travis', b'TRAVIS'), (b'belton', b'BELTON'), (b'decker', b'DECKER'), (b'canyon', b'CANYON'), (b'medina', b'MEDINA'), (b'austin', b'AUSTIN'), (b'bastrop', b'BASTROP'), (b'fayette', b'FAYETTE'), (b'buchanan', b'BUCHANAN'), (b'palestine', b'PALESTINE'), (b'lady-bird', b'LADY-BIRD'), (b'stillhouse', b'STILLHOUSE'), (b'marble-falls', b'MARBLE-FALLS'), (b'richland-chambers', b'RICHLAND-CHAMBERS')], max_length=10)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[(b'AK', b'Alaska'), (b'AL', b'Alabama'), (b'AR', b'Arkansas'), (b'AS', b'American Samoa'), (b'AZ', b'Arizona'), (b'CA', b'California'), (b'CO', b'Colorado'), (b'CT', b'Connecticut'), (b'DC', b'District of Columbia'), (b'DE', b'Delaware'), (b'FL', b'Florida'), (b'GA', b'Georgia'), (b'GU', b'Guam'), (b'HI', b'Hawaii'), (b'IA', b'Iowa'), (b'ID', b'Idaho'), (b'IL', b'Illinois'), (b'IN', b'Indiana'), (b'KS', b'Kansas'), (b'KY', b'Kentucky'), (b'LA', b'Louisiana'), (b'MA', b'Massachusetts'), (b'MD', b'Maryland'), (b'ME', b'Maine'), (b'MI', b'Michigan'), (b'MN', b'Minnesota'), (b'MO', b'Missouri'), (b'MP', b'Northern Mariana Islands'), (b'MS', b'Mississippi'), (b'MT', b'Montana'), (b'NA', b'National'), (b'NC', b'North Carolina'), (b'ND', b'North Dakota'), (b'NE', b'Nebraska'), (b'NH', b'New Hampshire'), (b'NJ', b'New Jersey'), (b'NM', b'New Mexico'), (b'NV', b'Nevada'), (b'NY', b'New York'), (b'OH', b'Ohio'), (b'OK', b'Oklahoma'), (b'OR', b'Oregon'), (b'PA', b'Pennsylvania'), (b'PR', b'Puerto Rico'), (b'RI', b'Rhode Island'), (b'SC', b'South Carolina'), (b'SD', b'South Dakota'), (b'TN', b'Tennessee'), (b'TX', b'Texas'), (b'UT', b'Utah'), (b'VA', b'Virginia'), (b'VI', b'Virgin Islands'), (b'VT', b'Vermont'), (b'WA', b'Washington'), (b'WI', b'Wisconsin'), (b'WV', b'West Virginia'), (b'WY', b'Wyoming')], default='TX', max_length=16)),
                ('paper', models.BooleanField(default=False)),
                ('num_days', models.IntegerField(default=1)),
                ('deleted', models.BooleanField(default=False)),
                ('participants', models.ManyToManyField(to='users.Profile')),
                ('results', models.ManyToManyField(to='results.TournamentResult')),
            ],
            options={
                'verbose_name_plural': 'Tournaments',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tournament',
            unique_together=set([('date', 'lake', 'city')]),
        ),
    ]
