# Generated by Django 2.1.4 on 2018-12-26 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anglers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_boater', models.BooleanField(default=False)),
                ('num_fish_dead', models.IntegerField(default=0)),
                ('num_fish_alive', models.IntegerField(default=0)),
                ('total_weight', models.FloatField(default=0.0)),
                ('big_bass_weight', models.FloatField(default=0.0)),
                ('penalty_deduction', models.FloatField(default=0.0)),
                ('angler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anglers.Angler')),
            ],
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boater', to='anglers.Angler')),
                ('non_boater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='non_boater', to='anglers.Angler')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('team', 'team'), ('individual', 'individual')], max_length=10)),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('ramp', models.CharField(max_length=128)),
                ('lake', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('paper', models.BooleanField(default=False)),
                ('num_days', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Tournaments',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tournament',
            unique_together={('date', 'lake', 'city')},
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournaments.Tournament'),
        ),
    ]
