# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='club_name',
            field=models.CharField(default=[('SABC', 'South Austin Bass Club')], max_length=128),
        ),
    ]
