# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_remove_tournament_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='club_name',
            field=models.CharField(default=(('SABC', 'South Austin Bass Club'),), max_length=128),
        ),
    ]
