# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_auto_20190110_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='club_name',
            field=models.CharField(choices=[('SABC', 'South Austin Bass Club')], default='SABC', max_length=128),
        ),
    ]
