# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_auto_20190110_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='club_name',
            new_name='organization',
        ),
    ]
