FROM python:3.11.1-alpine
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH="/app/sabc"
ENV DJANGO_SETTINGS_MODULE=sabc.settings
RUN apk --update add libxml2-dev libxslt-dev libffi-dev gcc musl-dev libgcc openssl-dev curl
RUN apk add jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev tree py3-pip
WORKDIR /app
COPY . .
RUN pip install -r requirements-mypy.txt
CMD ["python3", "-m", "pylint", "--load-plugins", "pylint_django", "--verbose", "sabc/tournaments/", "sabc/users/", "sabc/polls/", "--rcfile", "pyproject.toml"]