FROM python:3.11-alpine
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH="/app/sabc"
ENV UNITTEST=1
ENV DJANGO_DEBUG=1
WORKDIR /app
COPY . .
RUN apk add --no-cache gcc musl-dev && pip install -r requirements-pytest.txt
RUN python3 sabc/manage.py makemigrations --no-input -v 3 && python3 sabc/manage.py migrate --run-syncdb
RUN coverage run --branch --source=sabc -m pytest
CMD ["coverage", "report", "--show-missing"]