version: '3.9'

services:

  db:
    image: postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - db_vars.env

  sabc:
    env_file:
      - django_vars.env
    build: .
    container_name: sabc
    command: >
            sh -c "
            python sabc/manage.py makemigrations
            && python sabc/manage.py migrate --run-syncdb --noinput
            && ./create_superuser.sh
            && python sabc/manage.py runserver 0.0.0.0:80
            "
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 80:80
      - 587:587
    depends_on:
      - db
volumes:
  postgres_data:
  .: