FROM python:3.11.1-alpine
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH="/app/sabc"
WORKDIR /app
COPY . .
RUN pip install -r requirements-mypy.txt
CMD ["mypy", "--config-file", "pyproject.toml",  "/app/sabc"]