FROM python:3.11.1-alpine
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH="/app/sabc"
ENV DJANGO_DEBUG=1
WORKDIR /app
COPY . .
RUN apk add --no-cache gcc musl-dev && pip install -r requirements-mypy.txt
CMD ["mypy", "--config-file", "pyproject.toml",  "/app/sabc"]