app = "sabc-tournaments"
primary_region = "dfw"

[experimental]
  auto_rollback = true

[[mounts]]
  source = "sabc_data"
  destination = "/app/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[env]
  DATABASE_PATH = "/app/data/sabc.db"
  LOG_LEVEL = "INFO"

[deploy]
  release_command = "python core/database.py"