"""Model Constants"""


TOURNAMENT_TYPES = [
    ('team', 'TEAM'),
    ('individual', 'INDIVIDUAL')
]
LAKES = [
    ('tbd', 'TBD'),
    ('lbj', 'LBJ'),
    ('travis', 'TRAVIS'),
    ('belton', 'BELTON'),
    ('decker', 'DECKER'),
    ('canyon', 'CANYON'),
    ('medina', 'MEDINA'),
    ('austin', 'AUSTIN'),
    ('bastrop', 'BASTROP'),
    ('fayette', 'FAYETTE'),
    ('buchanan', 'BUCHANAN'),
    ('palestine', 'PALESTINE'),
    ('lady-bird', 'LADY-BIRD'),
    ('stillhouse', 'STILLHOUSE'),
    ('marble-falls', 'MARBLE-FALLS'),
    ('richland-chambers', 'RICHLAND-CHAMBERS')
]
STATES = [
    ('AK', 'Alaska'),
    ('AL', 'Alabama'),
    ('AR', 'Arkansas'),
    ('AS', 'American Samoa'),
    ('AZ', 'Arizona'),
    ('CA', 'California'),
    ('CO', 'Colorado'),
    ('CT', 'Connecticut'),
    ('DC', 'District of Columbia'),
    ('DE', 'Delaware'),
    ('FL', 'Florida'),
    ('GA', 'Georgia'),
    ('GU', 'Guam'),
    ('HI', 'Hawaii'),
    ('IA', 'Iowa'),
    ('ID', 'Idaho'),
    ('IL', 'Illinois'),
    ('IN', 'Indiana'),
    ('KS', 'Kansas'),
    ('KY', 'Kentucky'),
    ('LA', 'Louisiana'),
    ('MA', 'Massachusetts'),
    ('MD', 'Maryland'),
    ('ME', 'Maine'),
    ('MI', 'Michigan'),
    ('MN', 'Minnesota'),
    ('MO', 'Missouri'),
    ('MP', 'Northern Mariana Islands'),
    ('MS', 'Mississippi'),
    ('MT', 'Montana'),
    ('NA', 'National'),
    ('NC', 'North Carolina'),
    ('ND', 'North Dakota'),
    ('NE', 'Nebraska'),
    ('NH', 'New Hampshire'),
    ('NJ', 'New Jersey'),
    ('NM', 'New Mexico'),
    ('NV', 'Nevada'),
    ('NY', 'New York'),
    ('OH', 'Ohio'),
    ('OK', 'Oklahoma'),
    ('OR', 'Oregon'),
    ('PA', 'Pennsylvania'),
    ('PR', 'Puerto Rico'),
    ('RI', 'Rhode Island'),
    ('SC', 'South Carolina'),
    ('SD', 'South Dakota'),
    ('TN', 'Tennessee'),
    ('TX', 'Texas'),
    ('UT', 'Utah'),
    ('VA', 'Virginia'),
    ('VI', 'Virgin Islands'),
    ('VT', 'Vermont'),
    ('WA', 'Washington'),
    ('WI', 'Wisconsin'),
    ('WV', 'West Virginia'),
    ('WY', 'Wyoming')
]

PAPER_LENGTH_TO_WT = {
    12.0: 1.13,
    13.0: 1.25,
    13.5: 1.38,
    14.0: 1.50,
    14.5: 1.75,
    15.0: 2.00,
    15.5: 2.25,
    16.0: 2.50,
    16.5: 2.75,
    17.0: 3.00,
    17.5: 3.25,
    18.0: 3.50,
    18.5: 3.75,
    19.0: 4.00,
    19.5: 4.25,
    20.0: 4.50,
    20.5: 4.75,
    21.0: 5.00,
    21.5: 5.25,
    22.0: 5.50,
    22.5: 5.75,
    23.0: 6.00,
    23.5: 6.25,
    24.0: 6.50,
    24.5: 6.75,
    25.0: 7.00,
    25.5: 7.25,
    26.0: 7.50
}