# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualinfo',
            name='angler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Angler'),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='boater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boater', to='users.Angler'),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='non_boater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_boater', to='users.Angler'),
        ),
    ]
