"""Add indexes to all foreign key columns for performance

Revision ID: 1ed98f6d9bcc
Revises: 0e2a1aa4be4e
Create Date: 2025-11-17 10:43:24.112151

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ed98f6d9bcc"
down_revision: Union[str, None] = "0e2a1aa4be4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calendar_events")
    op.drop_table("dues")
    op.alter_column(
        "anglers", "member", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=True
    )
    op.alter_column(
        "anglers",
        "is_admin",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "anglers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.drop_constraint("anglers_email_key", "anglers", type_="unique")
    op.create_index(op.f("ix_anglers_email"), "anglers", ["email"], unique=False)
    op.alter_column(
        "events", "event_type", existing_type=sa.TEXT(), server_default=None, existing_nullable=True
    )
    op.alter_column(
        "events",
        "entry_fee",
        existing_type=sa.NUMERIC(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "is_cancelled",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=True,
    )
    op.drop_constraint("events_date_key", "events", type_="unique")
    op.create_index(op.f("ix_events_date"), "events", ["date"], unique=False)
    op.create_index(op.f("ix_events_year"), "events", ["year"], unique=False)
    op.alter_column(
        "lakes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "news",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "news",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "news", "published", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=True
    )
    op.alter_column(
        "news", "priority", existing_type=sa.INTEGER(), server_default=None, existing_nullable=True
    )
    op.alter_column(
        "news",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.create_index(op.f("ix_news_author_id"), "news", ["author_id"], unique=False)
    op.drop_constraint("officer_positions_position_year_key", "officer_positions", type_="unique")
    op.create_index(
        op.f("ix_officer_positions_angler_id"), "officer_positions", ["angler_id"], unique=False
    )
    op.create_index(op.f("ix_officer_positions_year"), "officer_positions", ["year"], unique=False)
    op.alter_column(
        "password_reset_tokens",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "password_reset_tokens",
        "used",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "password_reset_tokens",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "password_reset_tokens",
        "used_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.drop_index("idx_reset_tokens_token", table_name="password_reset_tokens")
    op.drop_constraint("password_reset_tokens_token_key", "password_reset_tokens", type_="unique")
    op.create_index(
        op.f("ix_password_reset_tokens_token"), "password_reset_tokens", ["token"], unique=False
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"), "password_reset_tokens", ["user_id"], unique=False
    )
    op.alter_column(
        "poll_options",
        "display_order",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=True,
    )
    op.create_index(op.f("ix_poll_options_poll_id"), "poll_options", ["poll_id"], unique=False)
    op.alter_column(
        "poll_votes",
        "voted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=True,
    )
    op.drop_index("idx_poll_votes_poll_angler", table_name="poll_votes")
    op.drop_index("idx_poll_votes_poll_id", table_name="poll_votes")
    op.create_index(op.f("ix_poll_votes_angler_id"), "poll_votes", ["angler_id"], unique=False)
    op.create_index(op.f("ix_poll_votes_option_id"), "poll_votes", ["option_id"], unique=False)
    op.create_index(op.f("ix_poll_votes_poll_id"), "poll_votes", ["poll_id"], unique=False)
    op.alter_column(
        "polls",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "polls", "closed", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=True
    )
    op.alter_column(
        "polls",
        "multiple_votes",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=True,
    )
    op.drop_index("idx_polls_event_dates", table_name="polls")
    op.create_index(op.f("ix_polls_created_by"), "polls", ["created_by"], unique=False)
    op.create_index(op.f("ix_polls_event_id"), "polls", ["event_id"], unique=False)
    op.alter_column(
        "ramps",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.create_index(op.f("ix_ramps_lake_id"), "ramps", ["lake_id"], unique=False)
    op.alter_column(
        "results",
        "num_fish",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "results",
        "total_weight",
        existing_type=sa.NUMERIC(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "results",
        "big_bass_weight",
        existing_type=sa.NUMERIC(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "results",
        "dead_fish_penalty",
        existing_type=sa.NUMERIC(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "results",
        "disqualified",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "results", "buy_in", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=True
    )
    op.alter_column(
        "results",
        "was_member",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=True,
    )
    op.drop_index("idx_results_tournament", table_name="results")
    op.create_index(op.f("ix_results_angler_id"), "results", ["angler_id"], unique=False)
    op.create_index(op.f("ix_results_tournament_id"), "results", ["tournament_id"], unique=False)
    op.alter_column(
        "team_results",
        "total_weight",
        existing_type=sa.NUMERIC(),
        server_default=None,
        existing_nullable=True,
    )
    op.drop_constraint("unique_tournament_team", "team_results", type_="unique")
    op.create_index(
        op.f("ix_team_results_angler1_id"), "team_results", ["angler1_id"], unique=False
    )
    op.create_index(
        op.f("ix_team_results_angler2_id"), "team_results", ["angler2_id"], unique=False
    )
    op.create_index(
        op.f("ix_team_results_tournament_id"), "team_results", ["tournament_id"], unique=False
    )
    op.alter_column(
        "tournaments",
        "fish_limit",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "tournaments",
        "entry_fee",
        existing_type=sa.NUMERIC(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "tournaments",
        "is_team",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "tournaments",
        "is_paper",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "tournaments",
        "big_bass_carryover",
        existing_type=sa.NUMERIC(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "tournaments",
        "complete",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "tournaments",
        "limit_type",
        existing_type=sa.TEXT(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "tournaments",
        "aoy_points",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=True,
    )
    op.create_index(op.f("ix_tournaments_created_by"), "tournaments", ["created_by"], unique=False)
    op.create_index(op.f("ix_tournaments_event_id"), "tournaments", ["event_id"], unique=False)
    op.create_index(op.f("ix_tournaments_lake_id"), "tournaments", ["lake_id"], unique=False)
    op.create_index(op.f("ix_tournaments_poll_id"), "tournaments", ["poll_id"], unique=False)
    op.create_index(op.f("ix_tournaments_ramp_id"), "tournaments", ["ramp_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tournaments_ramp_id"), table_name="tournaments")
    op.drop_index(op.f("ix_tournaments_poll_id"), table_name="tournaments")
    op.drop_index(op.f("ix_tournaments_lake_id"), table_name="tournaments")
    op.drop_index(op.f("ix_tournaments_event_id"), table_name="tournaments")
    op.drop_index(op.f("ix_tournaments_created_by"), table_name="tournaments")
    op.alter_column(
        "tournaments",
        "aoy_points",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=True,
    )
    op.alter_column(
        "tournaments",
        "limit_type",
        existing_type=sa.TEXT(),
        server_default=sa.text("'angler'::text"),
        existing_nullable=True,
    )
    op.alter_column(
        "tournaments",
        "complete",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=True,
    )
    op.alter_column(
        "tournaments",
        "big_bass_carryover",
        existing_type=sa.NUMERIC(),
        server_default=sa.text("0.0"),
        existing_nullable=True,
    )
    op.alter_column(
        "tournaments",
        "is_paper",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=True,
    )
    op.alter_column(
        "tournaments",
        "is_team",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=True,
    )
    op.alter_column(
        "tournaments",
        "entry_fee",
        existing_type=sa.NUMERIC(),
        server_default=sa.text("25.00"),
        existing_nullable=True,
    )
    op.alter_column(
        "tournaments",
        "fish_limit",
        existing_type=sa.INTEGER(),
        server_default=sa.text("5"),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_team_results_tournament_id"), table_name="team_results")
    op.drop_index(op.f("ix_team_results_angler2_id"), table_name="team_results")
    op.drop_index(op.f("ix_team_results_angler1_id"), table_name="team_results")
    op.create_unique_constraint(
        "unique_tournament_team",
        "team_results",
        ["tournament_id", "angler1_id", "angler2_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "team_results",
        "total_weight",
        existing_type=sa.NUMERIC(),
        server_default=sa.text("0.0"),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_results_tournament_id"), table_name="results")
    op.drop_index(op.f("ix_results_angler_id"), table_name="results")
    op.create_index("idx_results_tournament", "results", ["tournament_id"], unique=False)
    op.alter_column(
        "results",
        "was_member",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=True,
    )
    op.alter_column(
        "results",
        "buy_in",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=True,
    )
    op.alter_column(
        "results",
        "disqualified",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=True,
    )
    op.alter_column(
        "results",
        "dead_fish_penalty",
        existing_type=sa.NUMERIC(),
        server_default=sa.text("0.0"),
        existing_nullable=True,
    )
    op.alter_column(
        "results",
        "big_bass_weight",
        existing_type=sa.NUMERIC(),
        server_default=sa.text("0.0"),
        existing_nullable=True,
    )
    op.alter_column(
        "results",
        "total_weight",
        existing_type=sa.NUMERIC(),
        server_default=sa.text("0.0"),
        existing_nullable=True,
    )
    op.alter_column(
        "results",
        "num_fish",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_ramps_lake_id"), table_name="ramps")
    op.alter_column(
        "ramps",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_polls_event_id"), table_name="polls")
    op.drop_index(op.f("ix_polls_created_by"), table_name="polls")
    op.create_index(
        "idx_polls_event_dates", "polls", ["event_id", "starts_at", "closes_at"], unique=False
    )
    op.alter_column(
        "polls",
        "multiple_votes",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=True,
    )
    op.alter_column(
        "polls",
        "closed",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=True,
    )
    op.alter_column(
        "polls",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_poll_votes_poll_id"), table_name="poll_votes")
    op.drop_index(op.f("ix_poll_votes_option_id"), table_name="poll_votes")
    op.drop_index(op.f("ix_poll_votes_angler_id"), table_name="poll_votes")
    op.create_index("idx_poll_votes_poll_id", "poll_votes", ["poll_id"], unique=False)
    op.create_index(
        "idx_poll_votes_poll_angler", "poll_votes", ["poll_id", "angler_id"], unique=False
    )
    op.alter_column(
        "poll_votes",
        "voted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_poll_options_poll_id"), table_name="poll_options")
    op.alter_column(
        "poll_options",
        "display_order",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens")
    op.drop_index(op.f("ix_password_reset_tokens_token"), table_name="password_reset_tokens")
    op.create_unique_constraint(
        "password_reset_tokens_token_key",
        "password_reset_tokens",
        ["token"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index("idx_reset_tokens_token", "password_reset_tokens", ["token"], unique=False)
    op.alter_column(
        "password_reset_tokens",
        "used_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "password_reset_tokens",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "password_reset_tokens",
        "used",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=True,
    )
    op.alter_column(
        "password_reset_tokens",
        "expires_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_officer_positions_year"), table_name="officer_positions")
    op.drop_index(op.f("ix_officer_positions_angler_id"), table_name="officer_positions")
    op.create_unique_constraint(
        "officer_positions_position_year_key",
        "officer_positions",
        ["position", "year"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_news_author_id"), table_name="news")
    op.alter_column(
        "news",
        "expires_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "news",
        "priority",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=True,
    )
    op.alter_column(
        "news",
        "published",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=True,
    )
    op.alter_column(
        "news",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "news",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "lakes",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_events_year"), table_name="events")
    op.drop_index(op.f("ix_events_date"), table_name="events")
    op.create_unique_constraint(
        "events_date_key", "events", ["date"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "events",
        "is_cancelled",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "entry_fee",
        existing_type=sa.NUMERIC(),
        server_default=sa.text("25.00"),
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "event_type",
        existing_type=sa.TEXT(),
        server_default=sa.text("'sabc_tournament'::text"),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_anglers_email"), table_name="anglers")
    op.create_unique_constraint(
        "anglers_email_key", "anglers", ["email"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "anglers",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "anglers",
        "is_admin",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=True,
    )
    op.alter_column(
        "anglers",
        "member",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=True,
    )
    op.create_table(
        "dues",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("angler_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("year", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "amount",
            sa.NUMERIC(),
            server_default=sa.text("25.00"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("paid_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column(
            "paid",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="dues_pkey"),
        sa.UniqueConstraint(
            "angler_id",
            "year",
            name="dues_angler_id_year_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "calendar_events",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("event_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("event_type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint(
            "event_type = ANY (ARRAY['holiday'::text, 'sabc_tournament'::text, 'other_tournament'::text])",
            name="calendar_events_event_type_check",
        ),
        sa.PrimaryKeyConstraint("id", name="calendar_events_pkey"),
    )
    # ### end Alembic commands ###
