"""Change all CASCADE to RESTRICT for safer delete operations

Revision ID: 4ac79f8a3507
Revises: 1ed98f6d9bcc
Create Date: 2025-11-17 11:04:17.568474

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ac79f8a3507"
down_revision: Union[str, None] = "1ed98f6d9bcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("officer_positions_angler_id_fkey", "officer_positions", type_="foreignkey")
    op.create_foreign_key(
        None, "officer_positions", "anglers", ["angler_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_constraint(
        "password_reset_tokens_user_id_fkey", "password_reset_tokens", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "password_reset_tokens", "anglers", ["user_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_constraint("poll_options_poll_id_fkey", "poll_options", type_="foreignkey")
    op.create_foreign_key(None, "poll_options", "polls", ["poll_id"], ["id"], ondelete="RESTRICT")
    op.drop_constraint("poll_votes_option_id_fkey", "poll_votes", type_="foreignkey")
    op.drop_constraint("poll_votes_poll_id_fkey", "poll_votes", type_="foreignkey")
    op.drop_constraint("poll_votes_angler_id_fkey", "poll_votes", type_="foreignkey")
    op.create_foreign_key(None, "poll_votes", "polls", ["poll_id"], ["id"], ondelete="RESTRICT")
    op.create_foreign_key(None, "poll_votes", "anglers", ["angler_id"], ["id"], ondelete="RESTRICT")
    op.create_foreign_key(
        None, "poll_votes", "poll_options", ["option_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_constraint("ramps_lake_id_fkey", "ramps", type_="foreignkey")
    op.create_foreign_key(None, "ramps", "lakes", ["lake_id"], ["id"], ondelete="RESTRICT")
    op.drop_constraint("results_angler_id_fkey", "results", type_="foreignkey")
    op.drop_constraint("results_tournament_id_fkey", "results", type_="foreignkey")
    op.create_foreign_key(None, "results", "anglers", ["angler_id"], ["id"], ondelete="RESTRICT")
    op.create_foreign_key(
        None, "results", "tournaments", ["tournament_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_constraint("team_results_angler2_id_fkey", "team_results", type_="foreignkey")
    op.drop_constraint("team_results_angler1_id_fkey", "team_results", type_="foreignkey")
    op.drop_constraint("team_results_tournament_id_fkey", "team_results", type_="foreignkey")
    op.create_foreign_key(
        None, "team_results", "tournaments", ["tournament_id"], ["id"], ondelete="RESTRICT"
    )
    op.create_foreign_key(
        None, "team_results", "anglers", ["angler1_id"], ["id"], ondelete="RESTRICT"
    )
    op.create_foreign_key(
        None, "team_results", "anglers", ["angler2_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_constraint("tournaments_event_id_fkey", "tournaments", type_="foreignkey")
    op.create_foreign_key(None, "tournaments", "events", ["event_id"], ["id"], ondelete="RESTRICT")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade not recommended - reverting to CASCADE is dangerous.

    This migration changes foreign keys from CASCADE to RESTRICT for safety.
    Reverting this change would re-introduce the data loss risks that this
    migration was designed to prevent.
    """
    # To implement downgrade, you would need to:
    # 1. Find the auto-generated constraint names created in upgrade()
    # 2. Drop those constraints
    # 3. Re-create constraints with CASCADE
    # This is intentionally left unimplemented as downgrading is not recommended.
    pass
