"""Add archived field to news table

Revision ID: 79e50a317657
Revises: a1b2c3d4e5f6
Create Date: 2025-12-20 10:15:57.873306

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79e50a317657"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news", sa.Column("archived", sa.Boolean(), nullable=True, server_default="false")
    )
    # Set existing rows to not archived
    op.execute("UPDATE news SET archived = false WHERE archived IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news", "archived")
    # ### end Alembic commands ###
