FROM python:3.11-slim
ENV PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH="/app/sabc" \
    UNITTEST=1 \
    DJANGO_DEBUG=1 \
    DJANGO_SETTINGS_MODULE="sabc.settings" \
    POETRY_VERSION=1.8.0 \
    POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_NO_INTERACTION=1
ENV PATH=${POETRY_HOME}/bin:${PATH}

WORKDIR /app
COPY ../ .

RUN apt-get update && apt-get install -y gcc curl build-essential libpq-dev
RUN curl -sSL https://install.python-poetry.org | python3 -
RUN poetry config virtualenvs.create false
RUN poetry install --no-root
RUN python3 sabc/manage.py makemigrations --no-input -v 3 && python3 sabc/manage.py migrate --run-syncdb
RUN coverage run --branch --source=sabc -m pytest --capture=no -vv
CMD ["coverage", "report", "--show-missing"]
