services:

  db:
    container_name: sabc-data
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - db_vars.env

  sabc:
    container_name: sabc-webapp
    env_file:
      - django_vars.env
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: >
      sh -c "
      python sabc/manage.py makemigrations &&
      python sabc/manage.py migrate --run-syncdb --noinput &&
      docker/create_superuser.sh &&
      python sabc/manage.py runserver 0.0.0.0:80
      "
    volumes:
      - ..:/app
    ports:
      - 80:80
      - 587:587
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
