name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
    
    - name: Setup Nix Cache
      uses: cachix/cachix-action@v15
      with:
        name: devenv
        
    - name: Check code formatting
      run: nix develop -c ruff format --check .
      
    - name: Lint code
      run: nix develop -c make lint
      
    - name: Run tests
      env:
        UNITTEST: 1
      run: nix develop -c make test